import 'package:flutter/material.dart';

final ThemeData darkTheme = ThemeData(
  brightness: Brightness.dark,
  primaryColor: const Color(0xFF651CE5),
  scaffoldBackgroundColor: const Color(0xFF0c1014),
  visualDensity: VisualDensity.adaptivePlatformDensity,
  useMaterial3: true,
  fontFamily: 'SansSerif',
  appBarTheme: const AppBarTheme(
    backgroundColor: Color(0xFF651CE5),
    foregroundColor: Colors.white,
    elevation: 0,
    iconTheme: IconThemeData(color: Colors.white),
    titleTextStyle: TextStyle(
      color: Colors.white,
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
  ),
  colorScheme: ColorScheme.dark(
    primary: Color(0xFF651CE5),
    secondary: Color(0xFF0F3460),
    surface: Color(0xFF0c1014),
    error: Colors.redAccent,
    onPrimary: Colors.white,
    onSecondary: Colors.white,
    onSurface: Colors.white,
    onError: Colors.white,
  ),
  textTheme: const TextTheme(
    displayLarge: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
    titleLarge: TextStyle(color: Colors.white),
    bodyLarge: TextStyle(color: Colors.white70),
    bodyMedium: TextStyle(color: Colors.white60),
  ),
  iconTheme: const IconThemeData(color: Colors.white70),
  buttonTheme: const ButtonThemeData(
    buttonColor: Color(0xFF651CE5),
    textTheme: ButtonTextTheme.primary,
  ),
  cardColor: const Color(0xFF232946),
  dividerColor: Colors.white24,
  inputDecorationTheme: InputDecorationTheme(
    filled: true,
    fillColor: const Color(0xFF0c1014),
    border: OutlineInputBorder(
      borderRadius: BorderRadius.circular(16),
      borderSide: const BorderSide(color: Colors.white24),
    ),
    enabledBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(16),
      borderSide: const BorderSide(color: Colors.white24),
    ),
    focusedBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(16),
      borderSide: const BorderSide(color: Color(0xFF651CE5), width: 2),
    ),
    hintStyle: const TextStyle(color: Colors.white54),
    labelStyle: const TextStyle(color: Colors.white),
    iconColor: Colors.white70,
    contentPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
  ),
  snackBarTheme: const SnackBarThemeData(
    backgroundColor: Color(0xFF232946),
    contentTextStyle: TextStyle(color: Colors.white),
  ),
  primarySwatch: MaterialColor(0xff651CE5, {
    50: Color.fromRGBO(102, 28, 229, .1),
    100: Color.fromRGBO(102, 28, 229, .2),
    200: Color.fromRGBO(102, 28, 229, .3),
    300: Color.fromRGBO(102, 28, 229, .4),
    400: Color.fromRGBO(102, 28, 229, .5),
    500: Color.fromRGBO(102, 28, 229, .6),
    600: Color.fromRGBO(102, 28, 229, .7),
    700: Color.fromRGBO(102, 28, 229, .8),
    800: Color.fromRGBO(102, 28, 229, .9),
    900: Color.fromRGBO(102, 28, 229, 1),
  }),
);

final ThemeData lightTheme = ThemeData(
  brightness: Brightness.light,
  primaryColor: const Color(0xFF651CE5),
  scaffoldBackgroundColor: const Color(0xFFFFFFFF),
  visualDensity: VisualDensity.adaptivePlatformDensity,
  useMaterial3: true,
  fontFamily: 'SansSerif',
  appBarTheme: const AppBarTheme(
    backgroundColor: Color(0xFF651CE5),
    foregroundColor: Colors.white,
    elevation: 0,
    iconTheme: IconThemeData(color: Colors.white),
    titleTextStyle: TextStyle(
      color: Colors.white,
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
  ),
  colorScheme: ColorScheme.light(
    primary: Color(0xFF651CE5),
    secondary: Color(0xFF0F3460),
    surface: Color(0xffffffff),
    error: Colors.redAccent,
    onPrimary: Colors.white,
    onSecondary: Colors.white,
    onSurface: Colors.black,
    onError: Colors.white,
  ),
  textTheme: const TextTheme(
    displayLarge: TextStyle(color: Colors.black, fontWeight: FontWeight.bold),
    titleLarge: TextStyle(color: Colors.black),
    bodyLarge: TextStyle(color: Colors.black87),
    bodyMedium: TextStyle(color: Colors.black54),
  ),
  iconTheme: const IconThemeData(color: Colors.black54),
  buttonTheme: const ButtonThemeData(
    buttonColor: Color(0xFF651CE5),
    textTheme: ButtonTextTheme.primary,
  ),
  cardColor: Colors.white,
  dividerColor: Colors.black12,
  inputDecorationTheme: InputDecorationTheme(
    filled: true,
    fillColor: const Color(0xFFF5F6FA),
    border: OutlineInputBorder(
      borderRadius: BorderRadius.circular(16),
      borderSide: const BorderSide(color: Colors.black12),
    ),
    enabledBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(16),
      borderSide: const BorderSide(color: Colors.black12),
    ),
    focusedBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(16),
      borderSide: const BorderSide(color: Color(0xFF651CE5), width: 2),
    ),
    hintStyle: const TextStyle(color: Colors.black38),
    labelStyle: const TextStyle(color: Colors.black),
    iconColor: Colors.black54,
    contentPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
  ),
  snackBarTheme: const SnackBarThemeData(
    backgroundColor: Color(0xFF651CE5),
    contentTextStyle: TextStyle(color: Colors.white),
  ),
  primarySwatch: MaterialColor(0xff651CE5, {
    50: Color.fromRGBO(102, 28, 229, .1),
    100: Color.fromRGBO(102, 28, 229, .2),
    200: Color.fromRGBO(102, 28, 229, .3),
    300: Color.fromRGBO(102, 28, 229, .4),
    400: Color.fromRGBO(102, 28, 229, .5),
    500: Color.fromRGBO(102, 28, 229, .6),
    600: Color.fromRGBO(102, 28, 229, .7),
    700: Color.fromRGBO(102, 28, 229, .8),
    800: Color.fromRGBO(102, 28, 229, .9),
    900: Color.fromRGBO(102, 28, 229, 1),
  }),
);
