import 'package:flutter/material.dart';

final ThemeData darkTheme = ThemeData(
  brightness: Brightness.dark,
  primaryColor: const Color(0xFF651CE5),
  scaffoldBackgroundColor: const Color(0xFF181A20),
  visualDensity: VisualDensity.adaptivePlatformDensity,
  useMaterial3: true,
  fontFamily: 'SansSerif',
  appBarTheme: const AppBarTheme(
    backgroundColor: Color(0xFF232946),
    foregroundColor: Colors.white,
    elevation: 0,
    iconTheme: IconThemeData(color: Colors.white),
    titleTextStyle: TextStyle(
      color: Colors.white,
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
  ),
  colorScheme: ColorScheme.dark(
    primary: Color(0xFF651CE5),
    secondary: Color(0xFF0F3460),
    surface: Color(0xFF232946),
    background: Color(0xFF181A20),
    error: Colors.redAccent,
    onPrimary: Colors.white,
    onSecondary: Colors.white,
    onSurface: Colors.white,
    onBackground: Colors.white,
    onError: Colors.white,
  ),
  textTheme: const TextTheme(
    displayLarge: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
    titleLarge: TextStyle(color: Colors.white),
    bodyLarge: TextStyle(color: Colors.white70),
    bodyMedium: TextStyle(color: Colors.white60),
  ),
  iconTheme: const IconThemeData(color: Colors.white70),
  buttonTheme: const ButtonThemeData(
    buttonColor: Color(0xFF651CE5),
    textTheme: ButtonTextTheme.primary,
  ),
  cardColor: const Color(0xFF232946),
  dividerColor: Colors.white24,
  inputDecorationTheme: const InputDecorationTheme(
    filled: true,
    fillColor: Color(0xFF232946),
    border: OutlineInputBorder(),
    hintStyle: TextStyle(color: Colors.white54),
    labelStyle: TextStyle(color: Colors.white),
  ),
  snackBarTheme: const SnackBarThemeData(
    backgroundColor: Color(0xFF232946),
    contentTextStyle: TextStyle(color: Colors.white),
  ),
  primarySwatch: MaterialColor(0xff651CE5, {
    50: Color.fromRGBO(102, 28, 229, .1),
    100: Color.fromRGBO(102, 28, 229, .2),
    200: Color.fromRGBO(102, 28, 229, .3),
    300: Color.fromRGBO(102, 28, 229, .4),
    400: Color.fromRGBO(102, 28, 229, .5),
    500: Color.fromRGBO(102, 28, 229, .6),
    600: Color.fromRGBO(102, 28, 229, .7),
    700: Color.fromRGBO(102, 28, 229, .8),
    800: Color.fromRGBO(102, 28, 229, .9),
    900: Color.fromRGBO(102, 28, 229, 1),
  }),
);

final ThemeData lightTheme = ThemeData(
  brightness: Brightness.light,
  primaryColor: const Color(0xFF651CE5),
  scaffoldBackgroundColor: const Color(0xFFF5F6FA),
  visualDensity: VisualDensity.adaptivePlatformDensity,
  useMaterial3: true,
  // Correct property name and value
  fontFamily: 'SansSerif',
  appBarTheme: const AppBarTheme(
    backgroundColor: Color(0xFF651CE5),
    foregroundColor: Colors.white,
    elevation: 0,
    iconTheme: IconThemeData(color: Colors.white),
    titleTextStyle: TextStyle(
      color: Colors.white,
      fontSize: 20,
      fontWeight: FontWeight.bold,
    ),
  ),
  colorScheme: ColorScheme.light(
    primary: Color(0xFF651CE5),
    secondary: Color(0xFF0F3460),
    surface: Color(0xFFF5F6FA),
    background: Color(0xFFF5F6FA),
    error: Colors.redAccent,
    onPrimary: Colors.white,
    onSecondary: Colors.white,
    onSurface: Colors.black,
    onBackground: Colors.black,
    onError: Colors.white,
  ),
  textTheme: const TextTheme(
    displayLarge: TextStyle(color: Colors.black, fontWeight: FontWeight.bold),
    titleLarge: TextStyle(color: Colors.black),
    bodyLarge: TextStyle(color: Colors.black87),
    bodyMedium: TextStyle(color: Colors.black54),
  ),
  iconTheme: const IconThemeData(color: Colors.black54),
  buttonTheme: const ButtonThemeData(
    buttonColor: Color(0xFF651CE5),
    textTheme: ButtonTextTheme.primary,
  ),
  cardColor: Colors.white,
  dividerColor: Colors.black12,
  inputDecorationTheme: const InputDecorationTheme(
    filled: true,
    fillColor: Color(0xFFF5F6FA),
    border: OutlineInputBorder(),
    hintStyle: TextStyle(color: Colors.black38),
    labelStyle: TextStyle(color: Colors.black),
  ),
  snackBarTheme: const SnackBarThemeData(
    backgroundColor: Color(0xFF651CE5),
    contentTextStyle: TextStyle(color: Colors.white),
  ),
  primarySwatch: MaterialColor(0xff651CE5, {
    50: Color.fromRGBO(102, 28, 229, .1),
    100: Color.fromRGBO(102, 28, 229, .2),
    200: Color.fromRGBO(102, 28, 229, .3),
    300: Color.fromRGBO(102, 28, 229, .4),
    400: Color.fromRGBO(102, 28, 229, .5),
    500: Color.fromRGBO(102, 28, 229, .6),
    600: Color.fromRGBO(102, 28, 229, .7),
    700: Color.fromRGBO(102, 28, 229, .8),
    800: Color.fromRGBO(102, 28, 229, .9),
    900: Color.fromRGBO(102, 28, 229, 1),
  }),
);
